language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
script:
  - gradle check
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false

